-   repo: git://github.com/pre-commit/pre-commit-hooks.git
    sha: 4c90c9557da7c0d695d6a729bae8b1de4e496cbf
    hooks:
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: autopep8-wrapper
        args:
        - --in-place
        - --aggressive
        - --aggressive
        - --ignore=W503,E501
    -   id: flake8
        args:
        - --ignore=W503,E501,E265,E402,F405
