language: python
notifications:
  email: false
sudo: required
cache: pip
python:
- '2.6'
- '2.7'
- pypy
- '3.3'
- '3.4'
- '3.5'
- pypy3
services:
- docker
before_install:
- docker build -t coconut_tests -f dockerfiles/Dockerfile.execute_tests .
install:
- pip install "pip==7.1.2"
- make
script:
- docker run coconut_tests
# ensure that our container ran, and it's the only one that got run
- [[ $(docker ps -aq | wc -l) == 1 ]]
# get log of container that ran tests    | get results-line in last 20 | ensure 'passed' substring | abort/fail if this line contains 'fail' substring
- docker logs $(docker ps -aq) --tail 20 | grep ' seconds ===========' | grep -i 'passed' | grep -v 'fail'
deploy:
  provider: pypi
  user: evhub-develop
  password:
    secure: f5zfnO9cuMJyszSVG7h6ZZ0NtrQpI33NuCvyOEYeoLCL5815ANElRuBlGcP6KbydHM1rSp2/i62DXANy73U2mcPiQyiWUkhffOLxYnSGIMQ2hyRz2ZAopCusf5ZQFWH40NhT2q/gOnN/Cwyjd6KyU1oXSpolfROaE5aimu5dQcg=
  on:
    distributions: sdist bdist_wheel
    repo: evhub/coconut
    branch: develop

