# This install is NOT minimal!
#   TODO: Minimize the docker container
FROM debian:8.5
MAINTAINER x10an14

RUN apt-get update && apt-get install -y \
git \
python3 \
python3-pip

RUN ln -sf /usr/bin/pip3 /usr/bin/pip

# Copy source-code into docker image
ADD . /usr/coconut
WORKDIR /usr/coconut

# install
RUN make dev

# Open a console with current (source-code)
# version of Coconut
ENTRYPOINT ["python3", "coconut/main.py"]

