# This install is NOT minimal!
#   TODO: Minimize the docker container
FROM alpine:3.4
MAINTAINER x10an14

RUN apk add --no-cache \
    git \
    gcc \
    make \
    libzmq \
    python3 \
    python3-dev

RUN python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    rm -r /root/.cache

# Copy source-code into docker image
ADD . /usr/coconut
WORKDIR /usr/coconut

# install
RUN make dev

# Open a console with current (source-code)
# version of Coconut
ENTRYPOINT ["python3", "coconut/main.py"]

